name: Bug Report
description: File a bug report
labels: ["bug"]

body:
  - type: input
    id: shell-version
    attributes:
      label: GNOME Shell version
      description: >
        Output of `gnome-shell --version`
      placeholder: gnome-shell --version

  - type: dropdown
    id: session-type
    attributes:
      label: Session type
      multiple: false
      options:
        - "Xorg"
        - "Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)"

  - type: checkboxes
    id: flags
    attributes:
      label: Special configuration
      options:
        - label: High DPI
        - label: More than one monitor

  - type: input
    id: version
    attributes:
      label: ddterm version
      description: >
        Output of `gnome-extensions info ddterm@amezin.github.com | grep -Po 'Version:\s*\K\S+'`
      placeholder: gnome-extensions info ddterm@amezin.github.com | grep -Po 'Version:\s*\K\S+'

  - type: input
    id: distro
    attributes:
      label: Linux distro
      description: >
        Output of `grep -Po '^PRETTY_NAME=\K.*' /etc/os-release`
      placeholder: grep -Po '^PRETTY_NAME=\K.*' /etc/os-release

  - type: textarea
    id: dconf-dump
    attributes:
      label: ddterm settings dump
      description: >
        Output of `dconf dump /com/github/amezin/ddterm/`
      placeholder: dconf dump /com/github/amezin/ddterm/
      render: ini

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Description of the issue.

        Screenshots are appreciated, but not required.

        Also, you could save `journalctl -b` output to a file
        (`journactl -b >journal.txt`) and upload it here. However, check it
        for sensitive data before uploading (it may contain other application
        names, document/file names, window titles, etc.).

      placeholder: >
        Tip: You can attach images or log files by clicking this area to
        highlight it and then dragging files in.
