---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: [users]
        append: true
        password: "{{ 'vagrant' | password_hash('sha512', 'mysecretsalt') }}"
        password_lock: false

    - include_tasks: prepare-{{ ansible_facts['os_family'] | lower }}.yml
