name: bump version

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check-version.yml

  bump:
    needs: check

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

    - name: Setup Git user
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - run: .github/bump-version.sh

    - name: Push
      run: |
        git push
        git push --tags
