name: check version

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Read version from metadata
        id: get_version
        run: |
          echo "version=$(jq .version metadata.json.in)" >>$GITHUB_OUTPUT

      - name: Check version matches the tag
        run: |
          test v${{ steps.get_version.outputs.version }} = ${{ github.ref_name }}
