concurrency:
  group: ${{ github.workflow }}/${{ github.ref }}

name: pot

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - po/*.po
      - README.md
      - Vagrantfile
      - vagrant-provision/**

jobs:
  pot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:2023.12.26.0

    steps:
    - name: Get app token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_KEY }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}

    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

    - name: Enable generic error matcher
      run: echo "::add-matcher::.github/problem-matchers/generic.json"

    - name: Update .pot files
      run: po/update-pot.sh

    - name: Stage changes
      run: git add po/*.po po/*.pot

    - name: Commit
      uses: ddterm/github-api-commit-action@v0
      with:
        token: ${{ steps.app-token.outputs.token }}
        commit-message: 'Update translation files'
