concurrency:
  group: ${{ github.workflow }}/${{ github.ref }}
  cancel-in-progress: true

name: pot

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - po/*.po
      - README.md
      - Vagrantfile
      - vagrant-provision/**

jobs:
  pot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ddterm/ci-docker-image:2023.12.26.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

    - name: Enable generic error matcher
      run: echo "::add-matcher::.github/problem-matchers/generic.json"

    - name: Update .pot files
      run: po/update-pot.sh

    - name: Get app token
      id: app-token
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_KEY }}

    - name: Commit
      uses: getsentry/action-github-commit@v1.1.0
      with:
        github-token: ${{ steps.app-token.outputs.token }}
        message: 'Update translation files'
