name: pr

on:
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/common.yml
    if: ${{ startsWith(github.event.pull_request.head.ref, 'renovate/') || github.event.pull_request.base.repo.node_id != github.event.pull_request.head.repo.node_id }}
