name: push-po

concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - weblate
    tags-ignore:
      - v*
    paths:
      - po/*.po
      - po/*.pot

jobs:
  po:
    uses: ./.github/workflows/check-po.yml
