name: push-po

concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - v*
    paths:
      - po/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      testspace: false
