name: push

concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - renovate/**
      - weblate
    tags-ignore:
      - v*
    paths-ignore:
      - docs/**
      - po/**
      - README.md
      - Vagrantfile
      - vagrant-provision/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      testspace: true

  test:
    needs: build
    uses: ./.github/workflows/test.yml
