name: release

on:
  push:
    tags:
      - "v[0-9]+"
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Read version from metadata
        id: get_version
        run: |
          echo "version=$(jq .version metadata.json.in)" >>$GITHUB_OUTPUT

      - name: Check version matches the tag
        run: |
          test v${{ steps.get_version.outputs.version }} = ${{ github.ref_name }}

  build:
    uses: ./.github/workflows/build.yml

  draft:
    needs:
      - build
      - version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: pack
    - uses: softprops/action-gh-release@v1
      with:
        files: "*.shell-extension.zip"
        draft: true
        generate_release_notes: true
