name: release

on:
  push:
    tags:
      - "v[0-9]+"
  workflow_dispatch:

jobs:
  check-version:
    uses: ./.github/workflows/check-version.yml

  build:
    uses: ./.github/workflows/build.yml

  draft:
    needs:
      - build
      - check-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: pack
    - uses: softprops/action-gh-release@v1
      with:
        files: "*.shell-extension.zip"
        draft: true
        generate_release_notes: true
